### PR TITLE
fix: async api output object from extractOASchema

### PR DESCRIPTION
**Pull request by Acrontum-Carmichael**
Fixes: https://github.com/acrontum/generate-it/issues/64

### CODE REVIEW

**Review by p-mcgowan — APPROVED** [review]
Looks good.

I don't think the hashing will solve the underlying issue - it just means every change will fail the tests. At that point, depending on the issue that is being worked on, once the manual check shows that the output created the expected feature, then it's likely the user will just change the failing hash and call it a day - it's still possible (assuming they didn't check) that some parts of the output could possibly be removed, and go unnoticed.

I think for these tests, we should have an output schema and validate that it has neither additions nor missing fields - the original tests (unfortunately) only check if no existing fields changed, but since we don't always add to these tests, it would be easier to create a schema file then do `expect(output).toEqual(preGeneratedSchema)`
that way, any changes to the output schema will be highlighted in the failing test.

**Comment by Acrontum-Carmichael** [comment]
Yea absolutely, but i think we were already on the same page there. An additional and easy remedy here for the time being could be to add the generated test servers to git but ignore from npm. That way the developer will instantly see during run of tests, in context, what changed in the generated out put.  

This coupled with actual unit tests of everything would be ideal.

**Comment by p-mcgowan** [comment]
For sure - as long as it doesn't make the diffs / pulls really bloated with build files, but since it generates so much I feel like that woyld definitely be an issue

**Comment by Acrontum-Carmichael** [comment]
we can give it a go and see how it looks.. if it looks bonkers... press the retreat  button

**Pull request merged**
