### PR TITLE
add quick fix commands to updates

### PR DESCRIPTION
**Pull request by p-mcgowan**
Feature suggestion - open to ideas here

adds a quick fix tip after dependency changes (see image)

Motivation: copy pasting the console.table into an editor and running a macro is way too much effort...

### CODE REVIEW

**Comment by p-mcgowan** [comment]
adding WIP

I don't think it should suggest rolling back if the template package.json has older versions

**Comment by p-mcgowan** [comment]
Should be good to go now.

Rebased off master instead of dev, it was a few commits ahead... oops

I can fix it up if need be, just let me know.

**Comment by Acrontum-Carmichael** [comment]
@p-mcgowan i just got this error when running the tests:

src/lib/helpers/semverCompare.ts:12:18 - error TS2345: Argument of type 'string' is not assignable to parameter of type 'number'.

12     Number.isNaN(a1 + b1) ? 0 : +a1 - +b1 || a1.localeCompare(b1);
                    ~~~~~~
Found 1 error.

**Comment by Acrontum-Carmichael** [comment]
Also i released another fix for the rabbitmq logic, not sure i can merge in develop to your pr as the pr fork is owned by you

**Comment by p-mcgowan** [comment]
Cool - I'll fix up the number coercion - I'm surprised that didn't show up during my tests, that's a bit concerning.

Not sure what you mean with the fork - this PR branch is in the acrontum repo, but when I fix the other error I can rebase off dev again

**Comment by Acrontum-Carmichael** [comment]
Ah sorry my bad, you are right!

**Comment by p-mcgowan** [comment]
Not at my computer right now (see below), but I was unable to reproduce the TS error at home or in a fresh cloned project, so that's still a bit perplexing.

That being said, it actually produced the correct results through some js type-coercion wizardry, but TS didn't like it.

But, after re-reading it, it is better to reduce the "code golf" and split the compare methods as below.

Let me know if it works on your machine :)

Screenshot_20200523-182359

**Comment by Acrontum-Carmichael** [comment]
all tests pass, merged and published to npm

**Pull request merged**
