### PR TITLE
Enh/move templates to helper

### PR DESCRIPTION
**Pull request by p-mcgowan**
Move some hardcoded strings around in tests so that it's easier to change when manually testing non-master branches

### CODE REVIEW

**Comment by Acrontum-Carmichael** [comment]
looks good except the tests don't run in gh actions

**Comment by p-mcgowan** [comment]
need to fix the test files - might move the generated test code into a gitignored folder so it's clear they're just temp files

**Comment by p-mcgowan** [comment]
Ah, I see what's going on here - tests are running against old templates and not fetching from git.

I'm leaving this for another day - I just wanted to clean up some duplication but maybe it's better to not touch any of these for now

**Comment by p-mcgowan** [comment]
We will likely revist the tests at a later time - and if necessary refactor then

**Pull request closed without merging**
