### PR TITLE
Feature/nest domain1st grouping

### PR DESCRIPTION
**Pull request by Acrontum-Carmichael**
Existing tests all pass

New tests:  openapiNodegen_1stSegmentGrouping.ts

grouping works:
```     
 await openapiNodegen({
    dontRunComparisonTool: false,
    dontUpdateTplCache: true,
    mockServer: true,
    segmentFirstGrouping: 1,
    swaggerFilePath: ymlPath,
    targetDir: testServerPath,
    template: tplUrl,
});
```

unit test for the specific function:  src/lib/helpers/__tests__/endpointNameCalculation.ts

### CODE REVIEW

**Comment by p-mcgowan** [comment]
also these hash tests will break every time either the template or the code base changes.

Maybe we should think about what specifically should be tested for to ensure that this feature is unchanged when new ones are introduced

Are we checking that the template files are unchanged, or are we checking that passing in different params generates the same api schema with different naming conventions.

Personally, I think no tests are better than folder hashing tests - chances are, the more hash tests we have, the more time we spend blindly "fixing" tests as opposed to verifying it's doing what we want

**Comment by Acrontum-Carmichael** [comment]
Hmm strange - all tests pass for me

**Comment by Acrontum-Carmichael** [comment]
In general I agree, I introduced the hash tests as we had no unit test coverage. The hashes were the fastest was to ensure the output of new changes were correct. We currently still do not have enough unit test coverage though imo to remove the hash tests.

**Comment by Acrontum-Carmichael** [comment]
Which version of node are you running?

This end:
```
node -v && npm -v
v12.18.3
6.14.6

```

**Comment by p-mcgowan** [comment]
the same - 12.18.3 and 6.14.4 (LTS presumably)

Strange how it only ever works on one machine... :P

Yeah, I think it's fine for the time being - it will break when anything changes, but at least we will know...

I pushed up another branch with some of the changes we talked about last night - feel free to pull it in here or just merge this one in, but I thought it might be useful some time down the road


https://github.com/acrontum/generate-it/compare/feature/nestDomain1stGrouping...alternative-testing-strategy-suggestion

**Comment by Acrontum-Carmichael** [comment]
merged in - ran on an existing API and the generation was all good.

I will merge this into develop and release now, i'll be testing this feature on a new API today so will likely find any issues no seen yet

**Pull request merged**
