### PR TITLE
FEAT: transform all 200-level responses

### PR DESCRIPTION
**Pull request by p-mcgowan**
Extract the first 200-level response (as opposed to only 200), and use that for validation.

Use case: POST that returns the newly created entity, or a `runningJobId` (for example).

### CODE REVIEW

**Comment by p-mcgowan** [comment]
also requires changes to the templates 
https://github.com/acrontum/generate-it-typescript-server/pull/44

**Review by jeicken — APPROVED** [review]
Looking good to me - getting rid of this staticly set 200 response code logic seems like a very nice addition!

**Comment by Acrontum-Carmichael** [comment]
also this is going to master again not develop

**Comment by p-mcgowan** [comment]
oops - updated the base.

Makes sense, but should I tag it before or after the merge?

**Comment by Acrontum-Carmichael** [comment]
doesn't really matter than much.

but once you release the core and tpl try and tag the tpl as quick as possible to prevent issues.

**Pull request merged**
